[24-Feb-2024 00:09:03 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 56627200 bytes) in C:\Apache\htdocs\task-management\app\Models\User.php on line 53
[24-Feb-2024 10:14:51 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: View [404] not found. in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:137
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('404', Array)
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\Factory.php(137): Illuminate\View\FileViewFinder->find('404')
#2 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(88): Illuminate\View\Factory->make('404', Array)
#3 C:\Apache\htdocs\task-management\app\Exceptions\Handler.php(35): Illuminate\Routing\ResponseFactory->view('404', Array, 404)
#4 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(218): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException))
#5 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(InvalidArgumentException))
#6 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(InvalidArgumentException))
#7 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(InvalidArgumentException))
#8 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php on line 137
[24-Feb-2024 10:14:51 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: View [404] not found. in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:137
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('404', Array)
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\Factory.php(137): Illuminate\View\FileViewFinder->find('404')
#2 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(88): Illuminate\View\Factory->make('404', Array)
#3 C:\Apache\htdocs\task-management\app\Exceptions\Handler.php(35): Illuminate\Routing\ResponseFactory->view('404', Array, 404)
#4 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(218): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\ErrorHandler\Error\FatalError))
#5 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#6 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(231): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#7 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#8 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#9 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php on line 137
[24-Feb-2024 10:15:15 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: View [404] not found. in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:137
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('404', Array)
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\Factory.php(137): Illuminate\View\FileViewFinder->find('404')
#2 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(88): Illuminate\View\Factory->make('404', Array)
#3 C:\Apache\htdocs\task-management\app\Exceptions\Handler.php(35): Illuminate\Routing\ResponseFactory->view('404', Array, 404)
#4 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(218): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException))
#5 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(InvalidArgumentException))
#6 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(InvalidArgumentException))
#7 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(InvalidArgumentException))
#8 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php on line 137
[24-Feb-2024 10:15:15 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: View [404] not found. in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:137
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('404', Array)
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\Factory.php(137): Illuminate\View\FileViewFinder->find('404')
#2 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(88): Illuminate\View\Factory->make('404', Array)
#3 C:\Apache\htdocs\task-management\app\Exceptions\Handler.php(35): Illuminate\Routing\ResponseFactory->view('404', Array, 404)
#4 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(218): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\ErrorHandler\Error\FatalError))
#5 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#6 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(231): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#7 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#8 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#9 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php on line 137
[24-Feb-2024 10:16:40 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: View [404] not found. in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:137
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('404', Array)
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\Factory.php(137): Illuminate\View\FileViewFinder->find('404')
#2 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(88): Illuminate\View\Factory->make('404', Array)
#3 C:\Apache\htdocs\task-management\app\Exceptions\Handler.php(35): Illuminate\Routing\ResponseFactory->view('404', Array, 404)
#4 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(218): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException))
#5 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(InvalidArgumentException))
#6 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(InvalidArgumentException))
#7 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(InvalidArgumentException))
#8 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php on line 137
[24-Feb-2024 10:16:40 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: View [404] not found. in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:137
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('404', Array)
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\Factory.php(137): Illuminate\View\FileViewFinder->find('404')
#2 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(88): Illuminate\View\Factory->make('404', Array)
#3 C:\Apache\htdocs\task-management\app\Exceptions\Handler.php(35): Illuminate\Routing\ResponseFactory->view('404', Array, 404)
#4 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(218): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\ErrorHandler\Error\FatalError))
#5 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#6 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(231): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#7 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#8 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#9 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php on line 137
[24-Feb-2024 10:18:38 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: View [404] not found. in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:137
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('404', Array)
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\Factory.php(137): Illuminate\View\FileViewFinder->find('404')
#2 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(88): Illuminate\View\Factory->make('404', Array)
#3 C:\Apache\htdocs\task-management\app\Exceptions\Handler.php(38): Illuminate\Routing\ResponseFactory->view('404', Array, 404)
#4 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(218): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException))
#5 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(InvalidArgumentException))
#6 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(InvalidArgumentException))
#7 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(InvalidArgumentException))
#8 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php on line 137
[24-Feb-2024 10:18:38 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: View [404] not found. in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:137
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('404', Array)
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\Factory.php(137): Illuminate\View\FileViewFinder->find('404')
#2 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(88): Illuminate\View\Factory->make('404', Array)
#3 C:\Apache\htdocs\task-management\app\Exceptions\Handler.php(38): Illuminate\Routing\ResponseFactory->view('404', Array, 404)
#4 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(218): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\ErrorHandler\Error\FatalError))
#5 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#6 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(231): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#7 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#8 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#9 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php on line 137
[24-Feb-2024 10:32:52 UTC] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php:218
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#3 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php on line 218
[24-Feb-2024 10:32:52 UTC] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php:218
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(231): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#2 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#4 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php on line 218
[24-Feb-2024 10:32:54 UTC] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php:218
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#3 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php on line 218
[24-Feb-2024 10:32:54 UTC] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php:218
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(231): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#2 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#4 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php on line 218
[24-Feb-2024 10:33:06 UTC] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php:218
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Error))
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#3 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php on line 218
[24-Feb-2024 10:33:06 UTC] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php:218
Stack trace:
#0 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(195): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#1 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(231): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#2 C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#4 {main}
  thrown in C:\Apache\htdocs\task-management\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php on line 218
[24-Feb-2024 11:17:34 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 58724352 bytes) in C:\Apache\htdocs\task-management\app\Exceptions\Handler.php on line 34
[24-Feb-2024 11:18:48 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 58724352 bytes) in C:\Apache\htdocs\task-management\app\Exceptions\Handler.php on line 34
[24-Feb-2024 11:27:25 UTC] PHP Parse error:  Unclosed '{' on line 33 does not match ')' in C:\Apache\htdocs\task-management\app\Exceptions\Handler.php on line 48
[24-Feb-2024 11:27:25 UTC] PHP Parse error:  Unclosed '{' on line 33 does not match ')' in C:\Apache\htdocs\task-management\app\Exceptions\Handler.php on line 48
[24-Feb-2024 11:40:50 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 56627200 bytes) in C:\Apache\htdocs\task-management\app\Http\Middleware\CreatorTasksMiddleware.php on line 22
[24-Feb-2024 11:41:03 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 56627200 bytes) in C:\Apache\htdocs\task-management\app\Http\Middleware\CreatorTasksMiddleware.php on line 22
[24-Feb-2024 12:03:10 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 56627200 bytes) in C:\Apache\htdocs\task-management\app\Exceptions\Handler.php on line 47
[24-Feb-2024 12:04:28 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 56627200 bytes) in C:\Apache\htdocs\task-management\app\Exceptions\Handler.php on line 48
[24-Feb-2024 12:13:54 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 56627200 bytes) in C:\Apache\htdocs\task-management\app\Http\Middleware\CreatorTasksMiddleware.php on line 23
[24-Feb-2024 12:14:09 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 56627200 bytes) in C:\Apache\htdocs\task-management\app\Http\Middleware\CreatorTasksMiddleware.php on line 23
